# main text of home
title: Parikshit Sonwane
bio: Robotics & AI Engineer | UAV Systems | ML + Embedded + Control

# twitter summary info
description: A portfolio of robotics, ML, and UAV projects.

# better with square images
external-image: false
picture: assets/images/Profile.jpg

# your site color theme
dark-theme: auto

# Resume link
resume: true
resume-external: true
resume-url: https://drive.google.com/file/d/10P3IhvMINj5Y48_AV_jgoW55-u8d2b-f/view?usp=sharing

# your GitHub Pages URL
url: https://parikshit-06.github.io

permalink: /:title/

# analytics-google: 'UA-XXXXXXXXX-X'  # Uncomment and replace if using GA

# Disqus (optional — disable if you don’t need blog comments)
disqus:
  shortname: parikshit-06
  categories: [blog, project]

# Social media handles
facebook: 
twitter: 
instagram: 
linkedin: https://www.linkedin.com/in/psonwane/
github: parikshit-06
email: parik.sonwane06@gmail.com

authors:
  parikshit:
    name: Parikshit Sonwane
    bio: Robotics & AI Engineer | UAV Systems | ML + Embedded + Control
    external-image: false
    picture: assets/images/Profile.jpg
    twitter: 

# Layout width
width: normal

# Site sections
projects: true
about: true
blog: true

# Post features
read-time: true
show-tags: true
related: true
post-advance-links: [blog]
show-author: true
animation: true

# Default post behavior
defaults:
  - scope:
      path: ""
      layout: "post"
    values:
      hidden: false

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML compression
compress_html:
  ignore:
    envs:
      - development
      - stage

# Files to exclude from build
exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "vendor",
  ]
